# Generated by Django 4.1.7 on 2023-05-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_model', models.CharField(max_length=200)),
                ('date_sortie', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carburant', models.CharField(max_length=200)),
                ('kilometrage', models.IntegerField()),
                ('prix', models.FloatField()),
                ('nbr_place', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=5000)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemodele', to='voiture.modele')),
            ],
        ),
    ]
