# Generated by Django 4.1.7 on 2023-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nbr_place',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
